version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: dockerized-go:develop
    volumes:
      - $GOPATH/src:/go/src
    working_dir: /go/src/github.com/pouyanh/dockerized-go
