version: '2.3'
services:
  app:
    scale: 5
    build:
      context: ./service/app
      dockerfile: Dockerfile-dev
    image: registry.janstun.com/library/golang:develop
    working_dir: /go/src/github.com/pouyanh/dockerized-go
    volumes:
      - $GOPATH/src:/go/src
